# name: reviewdog
# on: [push]
# jobs:
#   markdownlint:
#     name: runner / markdownlint
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       # - name: markdownlint-github-check
#       #   uses: reviewdog/action-markdownlint@v0.1
#       #   with:
#       #     github_token: ${{ secrets.GITHUB_TOKEN }}
#       #     reporter: github-check
#       #     level: warning
#       #     filter_mode: nofilter
#       #     markdownlint_flags: '-r "./linting-rules/*" .'
#       - name: markdownlint-github-pr-review
#         uses: reviewdog/action-markdownlint@v0.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           reporter: github-check
#           level: warning
#           filter_mode: nofilter
#           markdownlint_flags: '--config ./.markdownlint.jsonc ./test/*'

name: reviewdog
on: [push]
jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: markdownlint-github-check
      #   uses: reviewdog/action-markdownlint@v0.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     reporter: github-check
      #     level: warning
      #     filter_mode: nofilter
      #     markdownlint_flags: '-r "./linting-rules/*" .'
      # - name: markdownlint-github-pr-review
      #   uses: reviewdog/action-markdownlint@v0.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     reporter: github-check
      #     level: warning
      #     filter_mode: nofilter
      #     markdownlint_flags: '--config ./.markdownlint.jsonc ./test/*'
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "''./test/*'"
          # config_file: ".markdownlint.jsonc"
          # ignore_files: "examples/ignore/*"
          rules: "'./linting-rules'"